# Site specific settings
title: "Kronin Cloud"
name: "Kronin Cloud"
keywords: "cloud, kubernetes, devops, remote work"
baseurl: "/"
url: "https://kronin.cloud"
description: "Our little companies website"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus: kronin.cloud
twitter: 
facebook: 
github: 
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
